# Generated by Django 2.0.3 on 2018-03-20 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AubsaigManufacturing',
            fields=[
                ('period', models.DateField(db_column='Period', primary_key=True, serialize=False)),
                ('value', models.DecimalField(blank=True, db_column='Value', decimal_places=2, max_digits=12, null=True)),
            ],
        ),
    ]
