# Generated by Django 2.0.3 on 2018-03-20 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('searching', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='indicator',
            unique_together={('name', 'country')},
        ),
    ]
