# Generated by Django 2.0.3 on 2018-03-20 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('searching', '0002_auto_20180320_1223'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='indicator',
            unique_together={('category', 'country', 'name')},
        ),
    ]
