# Generated by Django 2.0.3 on 2018-03-20 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('searching', '0004_charttype'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicator',
            name='api_url',
            field=models.CharField(default='default', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='indicator',
            name='chart_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='searching.ChartType'),
            preserve_default=False,
        ),
    ]
