# Generated by Django 2.0.3 on 2018-04-02 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searching', '0006_indicator_admin_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicator',
            name='admin_description',
            field=models.TextField(null=True),
        ),
    ]
