# Generated by Django 2.0.3 on 2018-04-02 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searching', '0007_auto_20180402_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicator',
            name='name',
            field=models.CharField(max_length=60),
        ),
    ]
