# Generated by Django 2.0.3 on 2018-04-02 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searching', '0008_auto_20180402_2023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicator',
            name='name',
            field=models.CharField(max_length=65),
        ),
    ]
